[package]
name = "ve_shader"
version = "0.1.0"
authors = ["Michael Lohr <michael@lohr-ffb.de>", "Shemnei"]
edition = "2018"

[dependencies]
structopt = "0.3.21"
shaderc = "0.6.1"
regex = "1.4.3"
glob = "0.3.0"
thiserror = "1.0.23"
log = "0.4.14"
env_logger = "0.8.2"
